package com.voxapps.datahygiene

/**
 * Contract each satellite's data layer implements once per entity type (Expense, CalendarEntry,
 * Note, ...) to detect an exact duplicate already in the database — same "one small interface per
 * entity type, shared scan logic underneath" shape as [RecordSanitizer].
 */
interface DuplicateChecker<T> {
    /** True if [candidate] and [existing] represent the same real-world record: every
     *  user-meaningful field matches after normalization (route strings through [FieldCleaner] so
     *  e.g. a "null"-string field and a genuinely blank one count as equal), ignoring identity/audit
     *  fields — an autogenerated id, a creation timestamp, an attached-photo filename, and the like. */
    fun isDuplicateOf(candidate: T, existing: T): Boolean
}

/** The first record in [existingRecords] that [candidate] duplicates, or null if none match — the
 *  shared "scan for it, don't reimplement the loop per entity" wrapper. */
fun <T> DuplicateChecker<T>.findDuplicate(candidate: T, existingRecords: List<T>): T? =
    existingRecords.firstOrNull { isDuplicateOf(candidate, it) }
