package com.voxapps.schema.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSValueArgument
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Nullability
import com.google.devtools.ksp.validate

private const val ANNOTATION_QUALIFIED_NAME = "com.voxapps.schema.VoxExtractionSchema"

/**
 * Generates a structural field schema (names, types, nullability — recursing into nested data
 * classes and `List<T>` item types) from any class annotated `@VoxExtractionSchema`. See the
 * annotation's own doc comment and the collapsed voice-command plan's section 4 for why: the
 * annotated class (e.g. `ExpenseParseResultParser.Parsed`) is already the ground truth for what
 * fields a satellite's extraction parser expects, so the schema should be generated from it rather
 * than hand-typed prose that can silently drift out of sync.
 */
class VoxSchemaProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_QUALIFIED_NAME)
        val (valid, invalid) = symbols.partition { it.validate() }

        valid.filterIsInstance<KSClassDeclaration>().forEach { classDecl ->
            generateSchemaFor(classDecl)
        }

        return invalid.toList()
    }

    private fun generateSchemaFor(classDecl: KSClassDeclaration) {
        val version = classDecl.annotations
            .first { it.shortName.asString() == "VoxExtractionSchema" }
            .arguments
            .firstVersionArgument()
            ?: 0

        val fieldsJson = describeProperties(classDecl, visited = mutableSetOf(classDecl.qualifiedName?.asString().orEmpty()))
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()
        val generatedObjectName = "Generated${className}Schema"

        val fileText = buildString {
            appendLine("package $packageName")
            appendLine()
            appendLine("// Generated by :core:schema-processor from @VoxExtractionSchema on $className.")
            appendLine("// Do not hand-edit — change $className's fields and rebuild instead.")
            appendLine("object $generatedObjectName {")
            appendLine("    const val VERSION: Int = $version")
            appendLine("    const val FIELD_SCHEMA_JSON: String = \"\"\"$fieldsJson\"\"\"")
            appendLine("}")
        }

        codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, classDecl.containingFile!!),
            packageName = packageName,
            fileName = generatedObjectName
        ).use { it.write(fileText.toByteArray()) }

        logger.info("Generated $generatedObjectName (version=$version) for $className")
    }

    private fun List<KSValueArgument>.firstVersionArgument(): Int? =
        firstOrNull { it.name?.asString() == "version" }?.value as? Int

    /** Builds a JSON array of `{"name":..,"type":..,"nullable":..}` from the class's primary
     *  constructor parameters only — deliberately not [KSClassDeclaration.getAllProperties], which
     *  would also pick up computed/derived properties (e.g. `Parsed.itemsSumMismatch`) that aren't
     *  part of the JSON shape the LLM is expected to produce. Recurses into nested data classes /
     *  `List<T>` element types (guarded by [visited] against infinite recursion). */
    private fun describeProperties(classDecl: KSClassDeclaration, visited: MutableSet<String>): String {
        val params = classDecl.primaryConstructor?.parameters.orEmpty()
        val props = params.map { describeProperty(it, visited) }
        return props.joinToString(prefix = "[", postfix = "]", separator = ",")
    }

    private fun describeProperty(param: KSValueParameter, visited: MutableSet<String>): String {
        val name = param.name?.asString().orEmpty()
        val type = param.type.resolve()
        val nullable = type.nullability == Nullability.NULLABLE
        val typeName = type.declaration.simpleName.asString()

        val nestedDecl = resolveNestedDataClass(type)
        val nestedJson = nestedDecl?.let { decl ->
            val qualified = decl.qualifiedName?.asString().orEmpty()
            if (qualified.isNotEmpty() && visited.add(qualified)) {
                describeProperties(decl, visited)
            } else {
                "[]" // already visited on this path — avoid infinite recursion on self-referential shapes
            }
        }

        return buildString {
            append("{\"name\":\"$name\",\"type\":\"$typeName\",\"nullable\":$nullable")
            nestedJson?.let { append(",\"fields\":$it") }
            append("}")
        }
    }

    /** If [type] is (or is a `List` of) a user-defined data class, returns that class declaration —
     *  used to recurse into e.g. `items: List<ParsedItem>` without needing a separate annotation on
     *  `ParsedItem`. Returns null for stdlib/primitive types. */
    private fun resolveNestedDataClass(type: KSType): KSClassDeclaration? {
        val decl = type.declaration as? KSClassDeclaration ?: return null
        val qualified = decl.qualifiedName?.asString().orEmpty()

        if (qualified == "kotlin.collections.List" || qualified == "kotlin.collections.MutableList") {
            val elementType = type.arguments.firstOrNull()?.type?.resolve() ?: return null
            return resolveNestedDataClass(elementType)
        }

        val isKotlinBuiltin = qualified.startsWith("kotlin.") || qualified.startsWith("java.")
        return if (!isKotlinBuiltin && decl.classKind.toString() == "CLASS") decl else null
    }
}

class VoxSchemaProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        VoxSchemaProcessor(environment.codeGenerator, environment.logger)
}
