package com.voxapps.voxconnect

import com.voxapps.logging.Logger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.util.UUID

/**
 * Completes a VoxConnect pairing after the phone scans a QR code shown on the PC. The PC generates
 * and displays the QR (it has to be the one showing it — phones reliably have a camera, many desktop
 * PCs don't); the phone then *pushes* its own freshly-minted session credential to a short-lived
 * listener the PC stands up just for this handshake, rather than the PC pulling one from an inbound
 * call to the phone. This is the reverse of a typical "server hands out an invite" pairing, forced by
 * the constraint that the phone has to stay the server for every request *after* pairing too (it's
 * the only side that can reach Commander/satellites via Android IPC) — see `VoxConnectServer`'s own
 * doc comment.
 *
 * QR payload (JSON, generated by the PC): `{"ip", "port", "key"}` — no correlation nonce, since
 * possessing [key] (only obtainable by actually scanning this exact QR) is already the proof that a
 * push claiming to answer it is legitimate.
 */
class VoxConnectPairing {

    /** Parses a scanned QR payload, mints a fresh credential for this phone's own server, and pushes
     *  it to the PC's temporary listener. Returns the new [PairedDevice] on success (the caller
     *  persists it via [PairedDeviceStore]) or null on any failure — malformed QR, unreachable PC, or
     *  a non-2xx response — so the UI can let the user rescan rather than fail silently. */
    suspend fun completeScannedPairing(qrPayload: String, phonePort: Int, phoneLabel: String): PairedDevice? {
        val qr = runCatching { JSONObject(qrPayload) }.getOrNull()
        val pcIp = qr?.optString("ip")?.takeIf { it.isNotBlank() }
        val pcPort = qr?.optInt("port", -1)?.takeIf { it > 0 }
        val qrKey = qr?.optString("key")?.takeIf { it.isNotBlank() }
            ?.let { runCatching { AesGcmCipher.keyFromBase64(it) }.getOrNull() }
        if (pcIp == null || pcPort == null || qrKey == null) {
            Logger.w(TAG, "Malformed pairing QR payload")
            return null
        }

        val deviceId = UUID.randomUUID().toString()
        val sessionKey = AesGcmCipher.generateKey()
        val pushBody = JSONObject()
            .put("deviceId", deviceId)
            .put("sessionKey", AesGcmCipher.keyToBase64(sessionKey))
            .put("port", phonePort)
            .put("label", phoneLabel)
            .toString()
        val encrypted = AesGcmCipher.encrypt(qrKey, pushBody)

        val pushed = withContext(Dispatchers.IO) { push(pcIp, pcPort, encrypted) }
        if (!pushed) return null

        return PairedDevice(
            deviceId = deviceId,
            label = "PC",
            sessionKey = sessionKey,
            pairedAt = System.currentTimeMillis()
        )
    }

    private fun push(ip: String, port: Int, encryptedBody: String): Boolean = try {
        val connection = URL("http://$ip:$port/pair-complete").openConnection() as HttpURLConnection
        connection.requestMethod = "POST"
        connection.doOutput = true
        connection.connectTimeout = CONNECT_TIMEOUT_MS
        connection.readTimeout = READ_TIMEOUT_MS
        connection.setRequestProperty("Content-Type", "text/plain; charset=utf-8")
        connection.outputStream.use { it.write(encryptedBody.toByteArray(Charsets.UTF_8)) }
        val ok = connection.responseCode in 200..299
        connection.disconnect()
        ok
    } catch (e: Exception) {
        Logger.w(TAG, "Pairing push to $ip:$port failed: ${e.message}")
        false
    }

    companion object {
        private const val TAG = "VoxConnectPairing"
        private const val CONNECT_TIMEOUT_MS = 5_000
        private const val READ_TIMEOUT_MS = 5_000
    }
}
