#!/bin/bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m'

log_info() { printf "${GREEN}%s${NC}\n" "$1"; }
log_warn() { printf "${YELLOW}%s${NC}\n" "$1"; }
log_error() { printf "${RED}%s${NC}\n" "$1"; }
log_blue() { printf "${BLUE}%s${NC}\n" "$1"; }

# Regenerates the "Build Status" table in README.md (between the LATEST_RELEASES:START/END
# markers) from the repo's actual GitHub Releases — never hand-edit tag numbers or APK sizes there,
# they go stale the moment any app's version is bumped (the APK size in particular used to be a
# hand-maintained snapshot in a separate table and drifted badly, e.g. Vox Vision sitting at a
# stale ~54 MB in README prose for several releases after R8 minification actually brought it down
# to ~4 MB — fetching the real published asset size here removes that whole class of staleness).
# Run manually (`./scripts/update_release_readme_links.sh`) or via
# `.github/workflows/update-readme-releases.yml`, which runs this on every `release: published`
# event so the table can't drift from what's actually published. Requires `gh` (authenticated) and
# `jq`.

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README_FILE="$PROJECT_ROOT/README.md"
REPO="razvan-eduard/VoxApps"

# app-prefix (tag prefix, also vox-<prefix> module dir) : Display Name : Vox<PascalCase> asset prefix
# Single source of truth for this mapping lives here — a new satellite app needs one new line.
APPS="
commander:Vox Commander:VoxCommander
calendar:Vox Calendar:VoxCalendar
expenses:Vox Expenses:VoxExpenses
notes:Vox Notes:VoxNotes
vision:Vox Vision:VoxVision
hub:Vox Hub:VoxHub
"

log_blue "🔍 Fetching releases from $REPO..."
ALL_RELEASES_JSON=$(gh api "repos/$REPO/releases" --paginate --jq '[.[] | select(.draft==false) | {tag: .tag_name, published_at: .published_at, prerelease: .prerelease, assets: [.assets[] | {name: .name, size: .size}]}]')

TABLE_ROWS=""
MISSING=""

while IFS=':' read -r prefix display asset_prefix; do
    [ -z "$prefix" ] && continue

    # Latest published release whose tag matches "<prefix>-v*" exactly (not a substring match —
    # "commander-v0.6-beta" must not match a hypothetical "commander-vision-v1" prefix collision).
    LATEST=$(echo "$ALL_RELEASES_JSON" | jq -r --arg p "$prefix" '
        [.[] | select(.tag | test("^" + $p + "-v"))] | sort_by(.published_at) | last
    ')

    if [ "$LATEST" = "null" ] || [ -z "$LATEST" ]; then
        MISSING="$MISSING $prefix"
        continue
    fi

    TAG=$(echo "$LATEST" | jq -r '.tag')
    PRERELEASE=$(echo "$LATEST" | jq -r '.prerelease')
    ASSET_NAME="${asset_prefix}-${TAG}.apk"
    ASSET_URL="https://github.com/$REPO/releases/download/$TAG/${ASSET_NAME}"
    RELEASE_URL="https://github.com/$REPO/releases/tag/$TAG"
    BADGE_URL="https://github.com/$REPO/actions/workflows/release-${prefix}.yml/badge.svg"
    WORKFLOW_URL="https://github.com/$REPO/actions/workflows/release-${prefix}.yml"

    LABEL="$TAG"
    if [ "$PRERELEASE" = "true" ]; then
        LABEL="$TAG (pre-release)"
    fi

    # Real published asset size, straight from the GitHub Release — not a hand-maintained snapshot
    # that can silently drift out of date (see the header comment above for why that mattered).
    SIZE_BYTES=$(echo "$LATEST" | jq -r --arg name "$ASSET_NAME" '.assets[] | select(.name == $name) | .size')
    if [ -n "$SIZE_BYTES" ] && [ "$SIZE_BYTES" != "null" ]; then
        SIZE_LABEL="$(awk -v b="$SIZE_BYTES" 'BEGIN { printf "%.1f MB", b / 1048576 }')"
    else
        SIZE_LABEL="—"
    fi

    TABLE_ROWS="${TABLE_ROWS}| **${display}** | [![Build](${BADGE_URL})](${WORKFLOW_URL}) | [\`${LABEL}\`](${RELEASE_URL}) | ${SIZE_LABEL} | [Download APK](${ASSET_URL}) |
"
done <<< "$APPS"

if [ -n "$MISSING" ]; then
    log_warn "⚠️  No published release found for:$MISSING (skipped in the table)"
fi

GENERATED_AT=$(date -u +"%Y-%m-%d")
BLOCK_FILE=$(mktemp)
trap 'rm -f "$BLOCK_FILE"' EXIT
cat > "$BLOCK_FILE" <<EOF
<!-- LATEST_RELEASES:START -->
<!-- Auto-generated by scripts/update_release_readme_links.sh — do not hand-edit. Regenerated on
     every GitHub release (see .github/workflows/update-readme-releases.yml). Last updated ${GENERATED_AT}. -->

| App | Build | Latest tag | APK size | Install |
|-----|-------|-----------|----------|---------|
${TABLE_ROWS}
<!-- LATEST_RELEASES:END -->
EOF

if ! grep -q "LATEST_RELEASES:START" "$README_FILE"; then
    log_error "❌ README.md has no <!-- LATEST_RELEASES:START --> marker — add it manually once, this script only replaces what's between the markers."
    exit 1
fi

# Portable in-place replace between markers (a temp-file + getline, not `awk -v` with an embedded
# multi-line string, which several awk implementations — including macOS's — mishandle: works with
# both GNU and BSD/macOS awk, unlike sed -i's differing -i syntax across platforms too).
awk -v blockfile="$BLOCK_FILE" '
    /<!-- LATEST_RELEASES:START -->/ {
        while ((getline line < blockfile) > 0) print line
        skip=1
        next
    }
    /<!-- LATEST_RELEASES:END -->/ { skip=0; next }
    !skip { print }
' "$README_FILE" > "$README_FILE.tmp" && mv "$README_FILE.tmp" "$README_FILE"

log_info "✅ README.md's Build Status table updated."
